version: '3.8'

services:

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: creditmanager
      MYSQL_PASSWORD: creditmanager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: creditmanager_db
