spring:
  datasource:
    url: jdbc:mysql://localhost/creditmanager_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: creditmanager
    password: creditmanager
  jpa:
    database: MYSQL
    show-sql: true

logging:
  level:
    com:
      endiluamba: INFO

jwt:
  secret: creditmanager
  validity: 18000